### ISSUE TITLE
Cross-listed courses taken at 5xx level not fulfilling requirements listed at 4xx level

### ISSUE THREAD

**Issue by fyy26** [upenn/irs#6]
A friend of mine finished 571 but it didn't show up to fulfill the 471 req.

**Comment by devietti** [comment]
Interesting, I tried to allow CIS 5710 everywhere CIS 4710 could be used. What majors are you seeing this with? If you could include a screenshot that would be helpful.

**Comment by fyy26** [comment]
CSCI BSE; just found that the course went under the TBS section 🤔
<img width="520" alt="image" src="https://user-images.githubusercontent.com/54198723/200396166-930da7af-cd68-4633-9744-d1d75dbb62dc.png">
<img width="537" alt="image" src="https://user-images.githubusercontent.com/54198723/200395698-1f85e4db-5a20-4aa3-a680-755c21f505b7.png">

**Comment by devietti** [comment]
Oh yeah, this is the Path@Penn worksheet, not IRS. But yes this is an issue! CIS 571 is also my class, as it turns out :-p If you try this out in IRS you should see more sensible results :-)

I submitted a fix a month or so ago to Path to no longer consider CIS 4710 as a humanities course, but it will only affect future iterations of the course. We are fixing up worksheets by hand, focusing on graduating seniors atm.
